### ISSUE TITLE
type(api.response_dict()) get not type dict

### ISSUE THREAD

**Issue by sunqianxiang** [timotheus/ebaysdk-python#109]
response = api.execute('GetCategories', {'LevelLimit':'1','DetailLevel':'ReturnAll','ViewAllNodes':True})
	
      print(type(api.response_dict()))
	<class 'ebaysdk.response.ResponseDataObject'>

tim

api.response_dict() the method get not dict().the does not match with the name.but **response.dict()** is success..there may be a misunderstanding

**Comment by timotheus** [comment]
api.response_dict() is a deprecated method call. It doesn't return an actual dictionary due to backward compatibility issues with legacy code. I will remove this method at some point. The response.dict() method should be used if you want a dictionary or response.reply if you want an object representation of the response.
