### ISSUE TITLE
aspect filter

### ISSUE THREAD

**Issue by Olimhon31** [timotheus/ebaysdk-python#310]
```
response = api.execute('findItemsAdvanced', {'keywords': 'camera',
                                            'paginationInput': {
                                                     'entriesPerPage':'10',
                                                     "pageNumber": '1'},
                                           'aspectFilter': [{"name":"Brand","value":"Sony"}]
                                                 }
                           )
```
I asked this question a month ago.  At that time i used `aspectName` instead of `name` . It gave me 0 product. And @fsmosca advised me to use `name` instead of `aspectName` . At that time it worked fine. But now `aspectFilter` doesnt work at all. Something was changed in new version of ebaysdk? THANK YOU!!!

**Comment by fsmosca** [comment]
I check this issue now and see that aspectName/aspectValueName returns the correct result.

### Lesson: the following is case sensitive
`aspectName/aspectValueName`  

If you use aspectname, with lowercase n, it will not follow the aspect filtering, **but still returns items** based on the keywords supplied. In the given keyword "camera" it will return canon or sony, etc brands.

### Wrong filter arguments are ignored
If you use `name/value`, same thing will happen. It will ignore the filtering but will go ahead and return items based on keywords supplied.

Ref. on aspectFilter: https://developer.ebay.com/DevZone/finding/CallRef/findItemsAdvanced.html#Request.aspectFilter


#### Ref.: Previous issue #299 regarding aspectFilter.

**Comment by fsmosca** [comment]
This one from issue #299 returns nothing,
```
response = api.execute('findItemsAdvanced',    {'keywords':'macbook',
                                                    'paginationInput': {
                                                    'entriesPerPage': '10',
                                                    "pageNumber": '1'
                                                    },
                                                  
'aspectFilter':[{'aspectName': 'Series', 'aspectValueName': 'MacBook Air'},
{'aspectName': 'Processor', 'aspectValueName': 'AMD A10'}]
}
```

 probably because apple does not use AMD processor.
[News on apple using amd processor.](https://www.tomshardware.com/news/apple-may-start-selling-macs-with-amd-cpus#:~:text=Although%20Apple%20offers%20Radeon%20graphics,the%20latest%20macOS%20Catalina%2010.15.&text=The%20code%20inside%20macOS%20Catalina%2010.15.)

The arguments here are correct, i.e. `aspectName/aspectValueName`. If you replace it with `name/value` as what I have suggested, it will ignore the filtering arguments and would instead return items based on the keyword `macbook`.
